# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be7d1fb83ea6a54c7e2bc544f70e45d34ece95c7421b03b87117302cf81e6d7e1edea6cdb8853dbbe91d12a65a51d122d48357cc0e5f158e74141e0d4057a716

test:
  secret_key_base: 163c88785452f733e4408cff4c1c3f105b6b63c4f47635b9fda08f9e7aa6686da99d206c707109b030476f59ccfaaed1fccbc7d9de63aab3e68d8e159d0c0940

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
